version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - mgl-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQUARE_ENVIRONMENT=${SQUARE_ENVIRONMENT:-sandbox}
      - SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
      - SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/mgl}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - mgl-network

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mgl
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mgl-network

networks:
  mgl-network:
    driver: bridge

volumes:
  postgres_data: 