version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_PUSH_BACKEND=websocket
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/New_York
      
      # Supabase Connection
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      
      # Square Connection
      - SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
      - SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID}
      - SQUARE_APP_ID=${SQUARE_APP_ID}
      - SQUARE_ENVIRONMENT=${SQUARE_ENVIRONMENT}
      - SQUARE_WEBHOOK_SIGNATURE_KEY=${SQUARE_WEBHOOK_SIGNATURE_KEY}
      
      # Email Notification Settings
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      
      # Database for n8n (SQLite by default, can use PostgreSQL)
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      
      # Execution settings
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336 # 14 days
      
      # Performance settings
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_TIMEOUT=300
      - EXECUTIONS_TIMEOUT_MAX=3600
      - MAX_WORKFLOW_OPERATION_COUNT=50000
      
      # Logging
      - N8N_LOG_LEVEL=info
      
    volumes:
      - n8n_data:/home/node/.n8n
      # Mount local workflow definitions for development
      - ./workflows:/home/node/.n8n/workflows

  # Optional: ngrok for exposing webhooks during development
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PORT=n8n:5678
    depends_on:
      - n8n

volumes:
  n8n_data:
    driver: local

# Create a .env file with these variables:
# N8N_ENCRYPTION_KEY=<random-32-character-string>
# SUPABASE_URL=<your-supabase-url>
# SUPABASE_ANON_KEY=<your-supabase-anon-key>
# SUPABASE_SERVICE_KEY=<your-supabase-service-key>
# SQUARE_ACCESS_TOKEN=<your-square-access-token>
# SQUARE_LOCATION_ID=<your-square-location-id>
# SQUARE_APP_ID=<your-square-app-id>
# SQUARE_ENVIRONMENT=sandbox
# SQUARE_WEBHOOK_SIGNATURE_KEY=<your-square-webhook-signature-key>
# SMTP_HOST=<your-smtp-host>
# SMTP_PORT=587
# SMTP_USER=<your-smtp-username>
# SMTP_PASS=<your-smtp-password>
# EMAIL_FROM=noreply@yourdomain.com
# NGROK_AUTH=<your-ngrok-auth-token> # Optional for dev 